[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python -m venv venv", "./venv/bin/pip install -r requirements.txt"]

[phases.start]
cmd = "./venv/bin/python app.py"
