[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["python -m venv venv", "./venv/bin/pip install -r voice_app/requirements.txt"]

[start]
cmd = "./venv/bin/python voice_app/app.py"
